name: Build Android APK

on:
  push:
    branches: [ main, master, android-ci-fix ]
  workflow_dispatch: {}

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Prepare Capacitor Android
        run: |
          if [ ! -d android ]; then
            npx cap add android --npm-client npm
          fi
          npx cap sync android
          test -f android/capacitor.settings.gradle && echo "Capacitor Android prepared"

      - name: Build Debug APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          which node || command -v node
          node -v
          ./gradlew -PnodeExecutable="$(which node || command -v node)" assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: desbin-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
